name: Project Submission
description: Submit your project
title: "[Project] <title>"
labels: [Project, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Did you attend the GitHub Workshop? 
    description: Please select ✅ if you have attended the GitHub Workshop
    options:
    - label: I have attended the GitHub Workshop
      required: true
- type: input
  attributes:
    label: Project Name
    description: Please add a name to your weekend project.
  validations:
    required: true
- type: input
  attributes:
    label: Project Repository
    description: Please share GitHub repository link of your project.
  validations:
    required: true
- type: input
  attributes:
    label: Project URL
    description: Please share demo link of your project or demo video.
  validations:
    required: true
- type: dropdown
  attributes:
    label: University Name
    description: University Name
    options:
      - Anurag University
      - D. Y. PATIL INSTITUTE OF MASTER OF COMPUTER APPLICATIONS AND MANAGEMENT
      - DR. D. Y. PATIL INSTITUTE OF ENGINEERING, MANAGEMENT
      - Gharda Institute of Technology
      - Gyan Ganga Institute of Technology
      - Indian Institute of Technology Tirupati
      - Ramco Institute of Technology
      - Sagar Institute of Science and Technology (SISTec)
      - Siddaganga Institute of Technology
      - SRINIVASA RAMANUJAN INSTITUTE OF TECHNOLOGY
      - SRM University-AP
      - SRINIVAS INSTITUTE OF TECHNOLOGY
      - SVKM's Institute of Technology
      - Toc H Institute of Science and Technology
      - Universal College of Engineering
  validations:
    required: true
- type: textarea
  attributes:
    label: Project Description
    description: |
      Links? References? Anything that will give us more context about your project!

      Tip: You can attach project details - pdf files, project presentation, images by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: dropdown
  attributes:
    label: GitHub Student Developer Pack Tools Used
    description: |
      Projects must use at least one tool from the Pack to be posted on the Student Gallery.
    multiple: true
    options:
      - Deepsource
      - Deepscan
      - pyCharm
      - Push Bots
      - Canva
      - Microsoft Azure
      - GitHub
      - ATOM
      - Mongo DB
      - Twilio
      - Pop SQL
      - Astra
      - WiseJ
      - LogDNA
  validations:
    required: true
